Fix int overflow in download percent Android
Cap-go/capacitor-updater pull request #160
Opened 2023-02-08 09:44 UTC by BorjaLive

When the update zip is above 21474836 bytes (~20MB), the current way of computing the downloaded percent overflows and returns a negative number.
This fix changes this line:
`final int newPercent = (int) ((bytesRead * 100) / totalLength);`
To:
`final int newPercent = (int) ((bytesRead / (float)totalLength) * 100);`

2023-02-09 09:19 UTC, luca-peruzzo commented
> When the update zip is above 21474836 bytes (~20MB), the current way of computing the downloaded percent overflows and returns a negative number. This fix changes this line: `final int newPercent = (int) ((bytesRead * 100) / totalLength);` To: `final int newPercent = (int) ((bytesRead / (float)totalLength) * 100);`

you used wrong variables, bytesRead and totalLenght are not defined in private File unzip function, maybe you mean to write ```final int newPercent = (int) ((lengthRead / (float)lengthTotal) * 100);``` at line 201?

2023-02-09 09:30 UTC, luca-peruzzo requested changes
it should be: ```final int newPercent = (int) ((lengthRead / (float)lengthTotal) * 100);```

2023-02-09 16:31 UTC, BorjaLive commented
I'm sorry, I made the changes in line 201 instead of 427. That's why the variable names don't match.
I've changed those two lines.

2023-02-10 02:09 UTC, riderx approved these changes

2023-02-10 02:09 UTC, merged